/* System Includes */
#include <string.h>
#include <stdlib.h>
/* Support Library */
#include <parse.h>
#include <std.h>
#include <err.h>

void populateSettingsWithFile(String filename) {
	initializeSettings();
	FILE *settings_file = fopen(filename,"r");
	char buffer[LINE];
	String key, value, sep;
	void *key_new, *value_new;
	String stream;
	
	stream = fgets(buffer, LINE, settings_file);
	do {
		if (buffer[0]=='#')
			goto end;	/* skip this line */
		sep = "=";
		key = strtok(buffer, sep);
		sep = "=\"\n#";
		value = strtok(NULL,sep);
		
		/* allocationg fresh resources */
		key_new = malloc(strlen(key)+1);
		strcpy(key_new, key);
		value_new = malloc(strlen(value)+1);
		strcpy(value_new, value);
		
		/* addind to internal data structure */
		addSetting(key_new, (void *)value_new);
		buffer[0] = '\0';
	end:
		stream = fgets(buffer, LINE, settings_file);
	} while (stream != NULL);
	
	fclose(settings_file);
}

void populateSettingsToFile(String filename) {
	settings.toFile = filename;
    //initializeSettings();
}

void unPopulateSettings(void) {
	int i = 0;
	for (; i < settings.count; i++) {
        free(settings.key[i]);
        free(settings.value[i]);
    }
    settings.count = 0;
}

void commitChanges(void) {
    if (settings.toFile == NULL) {
        err_log("No filename provided...");
        return;
    }
	FILE *save = fopen(settings.toFile,"w");
    int i = 0;
    fprintf(save, "# %s\n", SMALL_SEP);
    fprintf(save, "# This file was generated by the Note-Sync Program.\n");
    fprintf(save, "# (c) mitthu & Rishabh\n");
    fprintf(save, "# %s\n#\n", SMALL_SEP);
    
    for (; i < settings.count; i++) {
        fprintf(save, "%s=%s\n", settings.key[i], (char *)settings.value[i]);
    }
    
    fclose(save);
}

void initializeSettings(void) {
	settings.max_count = MAX_NUMBER_OF_SETTINGS;
	settings.count = 0;	/* shows actual item count */
}

int addSetting(String key, void *value) {
	int cnt = settings.count;
	
	if(cnt==settings.max_count)
		return FAILURE;
	settings.key[cnt] = key;
	settings.value[cnt] = value;
	cnt++; settings.count++;
	
	return SUCCESS;
}

/* Change the function so as to return a copy of the variable, not the original
 */
void* getSettingForKey(String key) {
	int cnt = settings.count;
	int i = 0;
	
	for (; i < cnt; i++)
		if (strcmp(key, settings.key[i]) == 0)
			return settings.value[i];
	return NULL;
}

int getSettingForKeyIntValue(String key) {
	return atoi((char*)getSettingForKey(key));
}

String getSettingForKeyStringValue(String key) {
	return (String)getSettingForKey(key);
}

bool getSettingForKeyBoolValue(String key) {
	char buf[LINE];
	strcpy(buf, getSettingForKey(key));
	
	/* checking for trailing spaces */
	int len = strlen(buf);
	while (buf[len-1] == ' ') {
		buf[len-1] = '\0';
		len--;
	}
	
	if (strcmp(buf, "YES") == 0)
		return YES;
	else if (strcmp(buf, "NO") == 0)
		return NO;
	
	err_log("Bool Setting cannot be verified");
	err_log("\tagainst key: %s, value: %s", key, buf);
	return NO;
}

void printAllSettings(void) {
	int cnt = settings.count, i = 0;
    printf("%s\n", SMALL_SEP);
	for (; i < cnt; i++)
		printf("Key:\t%s\nValue:\t%s\n%s\n", settings.key[i], (String)settings.value[i], SMALL_SEP);
}
